stages:
  - test
  - deploy
test-my-project:
  image: golang:1.7
  stage: test
  script:
    - go get github.com/tools/godep
    - mkdir -p /go/src/gitlab.com/jcloutz
    - cp -r /builds/jcloutz /go/src/gitlab.com/
    - cd /go/src/gitlab.com/jcloutz/fcc-go-header-parser-microservice
    - godep restore
    - godep go test -v -cover ./...
staging:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=sheltered-woodland-52848 --api-key=$HEROKU_API_DEPLOY_KEY
  only:
    - master
